### ISSUE TITLE
Fatal error na página de carrinho desde versão 2.8.0

### ISSUE THREAD

**Issue by plovinicius** [melhorenvio/wp-melhorenvio-v2#44]
Desde a versão 2.8.0 o plugin está dando problema, tentei atualizar para a versão atual (v2.9.1) porém o problema continua. 
Quando tenta acessar a página do carrinho no WordPress + WooCommerce, ele da o seguinte log no servidor:

```
PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in /var/www/vhosts/URL_SITE/httpdocs/wp-content/plugins/melhor-envio-cotacao/Services/QuotationService.php:202\nStack trace:\n#0 /var/www/vhosts/URL_SITE/httpdocs/wp-content/plugins/melhor-envio-cotacao/Services/QuotationService.php(172): Services\\QuotationService->isSessionCachedQuotationExpired(Array)\n#1 /var/www/vhosts/URL_SITE/httpdocs/wp-content/plugins/melhor-envio-cotacao/Services/QuotationService.php(61): Services\\QuotationService->getSessionCachedQuotation(Array, 1)\n#2 /var/www/vhosts/URL_SITE/httpdocs/wp-content/plugins/melhor-envio-cotacao/Services/CalculateShippingMethodService.php(46): Services\\QuotationService->calculateQuotationByProducts(Array, '', 1)\n#3 /var/www/vhosts/URL_SITE/httpdocs/wp-content/plugins/melhor-envio-cotacao/services_methods/class-wc-melhor-envio-shipping.php(114): Services\\CalculateShippingMethodService->calculateShipping(Array, 1, 1...\n', referer: https://URL_SITE/produto/nome-do-produto/
```

**Comment by viniciustessmann** [comment]
Olá @plovinicius 
Sabes me informar se esse problema continua nas versões mais atuais?
Obrigado.
